wip: try to fix workflow some more

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -6,7 +6,6 @@ on:
   workflow_dispatch: {}
 jobs:
   build:
-    needs: install-dependencies
     runs-on: ubuntu-latest
     permissions:
       contents: write
@@ -25,27 +24,22 @@ jobs:
         with:
           node-version: 18.x
       - name: Install dependencies
-        run: bun install
+        run: npm install -g bun && bun install
       - name: build
         run: npx projen build
       - name: Find mutations
         id: self_mutation
-        run: |-
-          git add .
-          git diff --staged --patch --exit-code > .repo.patch || echo "self_mutation_happened=true" >> $GITHUB_OUTPUT
+        run: git add . && git diff --staged --patch --exit-code > .repo.patch || echo "self_mutation_happened=true" >> $GITHUB_ENV
       - name: Upload patch
         if: steps.self_mutation.outputs.self_mutation_happened
         uses: actions/upload-artifact@v4
         with:
           name: .repo.patch
           path: .repo.patch
-          overwrite: true
+          overwrite: "true"
       - name: Fail build on mutation
         if: steps.self_mutation.outputs.self_mutation_happened
-        run: |-
-          echo "::error::Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch."
-          cat .repo.patch
-          exit 1
+        run: echo "::error::Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch." && cat .repo.patch && exit 1
       - name: Backup artifact permissions
         run: cd dist && getfacl -R . > permissions-backup.acl
         continue-on-error: true
@@ -54,7 +48,7 @@ jobs:
         with:
           name: build-artifact
           path: dist
-          overwrite: true
+          overwrite: "true"
   self-mutation:
     needs: build
     runs-on: ubuntu-latest
@@ -111,14 +105,3 @@ jobs:
         run: cd .repo && npx projen package:js
       - name: Collect js Artifact
         run: mv .repo/dist dist
-  install-dependencies:
-    runs-on: ubuntu-latest
-    permissions:
-      contents: write
-    steps:
-      - name: Setup Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: 18.x
-      - name: Install bun
-        run: npm i -g bun
